# Generated by Django 4.2.7 on 2025-11-24 15:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sevis_pass_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('grade_level', models.IntegerField(choices=[(11, 'Grade 11'), (12, 'Grade 12')])),
                ('school', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeaknessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('math', 'Mathematics'), ('english', 'English')], max_length=50)),
                ('weaknesses', models.JSONField(default=dict, help_text='Dictionary of topic:weakness_score pairs')),
                ('strengths', models.JSONField(default=dict, help_text='Dictionary of topic:strength_score pairs')),
                ('baseline_score', models.FloatField(default=0.0, help_text='Overall baseline score percentage')),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence in analysis (0.0 to 1.0)')),
                ('recommended_difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weakness_profiles', to='core.user')),
            ],
            options={
                'db_table': 'weakness_profiles',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('math', 'Mathematics'), ('english', 'English')], max_length=50)),
                ('metric_name', models.CharField(help_text="Metric being tracked (e.g., 'algebra_score', 'reading_comprehension')", max_length=100)),
                ('metric_value', models.FloatField(help_text='Value of the metric')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='core.user')),
            ],
            options={
                'db_table': 'progress',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['user', 'subject', 'recorded_at'], name='progress_user_id_2c3be1_idx'), models.Index(fields=['user', 'metric_name', 'recorded_at'], name='progress_user_id_b91784_idx')],
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('math', 'Mathematics'), ('english', 'English')], max_length=50)),
                ('week_plan', models.JSONField(default=dict, help_text='Week-by-week learning plan structure')),
                ('daily_tasks', models.JSONField(default=dict, help_text='Daily micro-lessons and practice tasks')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to='core.user')),
            ],
            options={
                'db_table': 'learning_paths',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'subject', 'status'], name='learning_pa_user_id_7abc22_idx')],
            },
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('math', 'Mathematics'), ('english', 'English')], max_length=50)),
                ('question', models.TextField()),
                ('student_answer', models.TextField()),
                ('correct_answer', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0, help_text='Question score (0.0 to 1.0)')),
                ('time_taken_seconds', models.IntegerField(default=0, help_text='Time taken to answer in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='core.user')),
            ],
            options={
                'db_table': 'diagnostics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'subject', 'created_at'], name='diagnostics_user_id_e3e738_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('math', 'Mathematics'), ('english', 'English')], max_length=50)),
                ('messages', models.JSONField(default=list, help_text='List of chat messages with role and content')),
                ('context', models.JSONField(default=dict, help_text='Additional context for AI (weaknesses, grade level, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='core.user')),
            ],
            options={
                'db_table': 'chat_sessions',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'subject', 'updated_at'], name='chat_sessio_user_id_186b4c_idx')],
            },
        ),
    ]
