# Generated by Django 4.2.7 on 2025-11-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', help_text='Hashed password for MVP', max_length=255),
        ),
    ]
