# Generated by Django 4.2.7 on 2025-11-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='syllabus',
            field=models.JSONField(default=dict, help_text='Comprehensive syllabus/curriculum outline for the subject'),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='week_plan',
            field=models.JSONField(default=dict, help_text='Week-by-week learning plan structure with learning materials'),
        ),
    ]
