# Generated by Django 4.2.7 on 2025-11-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_learningpath_syllabus_alter_learningpath_week_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='subject',
            field=models.CharField(choices=[('math', 'Mathematics')], default='math', max_length=50),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='subject',
            field=models.CharField(choices=[('math', 'Mathematics')], default='math', max_length=50),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='subject',
            field=models.CharField(choices=[('math', 'Mathematics')], default='math', max_length=50),
        ),
        migrations.AlterField(
            model_name='progress',
            name='subject',
            field=models.CharField(choices=[('math', 'Mathematics')], default='math', max_length=50),
        ),
        migrations.AlterField(
            model_name='weaknessprofile',
            name='subject',
            field=models.CharField(choices=[('math', 'Mathematics')], default='math', max_length=50),
        ),
    ]
